# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Capabilities",
    "Device",
    "DeviceBusy",
    "DeviceNotFound",
    "Discovery",
    "MediaError",
    "ScanCancelled",
    "ScanResult",
    "ScannerError",
    "Session",
    "TransientError",
    "TransportError",
    "UnsupportedError",
    "init_logging",
    "list_devices",
]

@typing.final
class Capabilities:
    r"""
    What the scanner says it can do, projected down to what a caller needs to
    place a scan. Grows as bindings turn up a real need for more of it
    """
    @property
    def vendor(self) -> builtins.str: ...
    @property
    def product(self) -> builtins.str: ...
    @property
    def revision(self) -> builtins.str: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @property
    def x_dpi_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def y_dpi_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def optical_dpi(self) -> builtins.int: ...
    @property
    def max_frames(self) -> builtins.int:
        r"""
        Frames the loaded holder can hold, 0 where the unit publishes no table
        """
    @property
    def thumbnail_dpi(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The thumbnail pass's resolution range, empty where there is no thumbnail
        """
    @property
    def focus_range(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Focus positions the unit accepts
        """
    @property
    def max_samples(self) -> builtins.int:
        r"""
        Most readings of one line a pass may ask for. 1 where the unit reads a
        line one time, so a multi-sample control can be hidden
        """
    @property
    def framing(self) -> builtins.str:
        r"""
        How this unit finds frames: "published", "thumbnail", "perforation" or
        "address". Only the middle two take a thumbnail pass
        """
    @property
    def thumbnail(self) -> builtins.bool:
        r"""
        Whether a thumbnail pass happens at all, and so whether a caller can
        offer to keep it
        """
    @property
    def multi_line(self) -> builtins.bool:
        r"""
        Whether the CCD can read its lines at once. False means a "superfine"
        control has nothing to switch
        """
    @property
    def eject(self) -> builtins.bool:
        r"""
        Whether the unit can give the medium back on its own
        """
    @property
    def autofocus(self) -> builtins.bool:
        r"""
        Whether the unit focuses itself
        """
    @property
    def hardware_metering(self) -> builtins.bool:
        r"""
        Whether the unit runs an AE pass itself. False on every unit seen, an
        LS-9000 included, so metering is host-side and the white-balance
        controls are what decide it
        """
    @property
    def interleavings(self) -> builtins.list[builtins.str]:
        r"""
        The reading modes this unit offers, by name
        """
    @staticmethod
    def locks_white_balance(film: builtins.str) -> builtins.bool:
        r"""
        Whether this film type is metered with its channels held together
        
        The default a `lock_white_balance` control should start from. It follows
        the film rather than the scanner, so it is the same answer everywhere -
        it lives here because this is where a caller already looks
        """

@typing.final
class Device:
    r"""
    A scanner this library found, and can open
    """
    @property
    def location(self) -> builtins.str:
        r"""
        Where it is
        """
    @property
    def name(self) -> builtins.str:
        r"""
        What to show a person
        """
    def __repr__(self) -> builtins.str: ...

class DeviceBusy(TransientError):
    r"""
    Something else has the scanner
    """
    ...

class DeviceNotFound(ScannerError):
    r"""
    No such scanner
    """
    ...

@typing.final
class Discovery:
    r"""
    What discovery found
    """
    @property
    def frames(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.int, builtins.int]]: ...
    @property
    def thumbnail(self) -> typing.Optional[builtins.dict[builtins.str, numpy.typing.NDArray[numpy.uint16]]]:
        r"""
        One array per channel, keyed the way `ScanResult.colors` is;
        `None` where the mechanism that found `frames` needed no thumbnail pass
        """
    @property
    def addresses_per_column(self) -> typing.Optional[builtins.float]:
        r"""
        Feed addresses one column of `thumbnail` spans
        
        Use this to put a rectangle drawn on the thumbnail onto the film, so the
        rectangle previewed is the rectangle scanned. Do not compute it as
        `optical_dpi / thumbnail_dpi`: the film does not keep to the thumbnail
        resolution the unit reports, and the error accumulates along the strip.
        Measured per pass, so read it from each discovery and do not cache it.
        `None` where the mechanism took no thumbnail
        """

class MediaError(ScannerError):
    r"""
    Something a person has to go fix
    """
    ...

class ScanCancelled(ScannerError):
    r"""
    A progress callback returned False
    """
    ...

@typing.final
class ScanResult:
    r"""
    What one frame's scan produced
    """
    @property
    def colors(self) -> builtins.dict[builtins.str, numpy.typing.NDArray[numpy.uint16]]:
        r"""
        One array per captured channel, keyed by name ("red", "green", "blue", ...)
        """
    @property
    def ir(self) -> typing.Optional[numpy.typing.NDArray[numpy.uint16]]:
        r"""
        The infrared plane, where the recipe asked for it
        """
    @property
    def dpi(self) -> builtins.int: ...
    @property
    def rows(self) -> builtins.int: ...
    @property
    def cols(self) -> builtins.int: ...
    @property
    def exposures(self) -> builtins.dict[builtins.str, builtins.int]:
        r"""
        What the frame was exposed at, keyed the same way as `colors`
        """
    @property
    def cleaned(self) -> typing.Optional[builtins.int]:
        r"""
        Pixels dust removal rebuilt, where asked for
        """

class ScannerError(builtins.RuntimeError):
    r"""
    Base for every error this crate raises
    """
    ...

@typing.final
class Session:
    r"""
    An open, exclusive hold of a scanner
    """
    @property
    def capabilities(self) -> Capabilities:
        r"""
        What the scanner says it can do
        """
    def __new__(cls, location: builtins.str) -> Session:
        r"""
        Start a session against whatever `list_devices` reports at this `location`
        """
    @staticmethod
    def open(device: Device) -> Session:
        r"""
        Start a session against `device`
        """
    def media_loaded(self) -> builtins.bool:
        r"""
        Whether a holder is loaded
        """
    def stage(self) -> None:
        r"""
        Put the unit in the state a scan expects
        """
    def eject(self) -> builtins.bool:
        r"""
        Give back whatever is loaded, answering whether the unit did anything
        """
    def load(self) -> builtins.bool:
        r"""
        Take in whatever the adapter has waiting, answering whether anything came
        """
    def discover_frames(self, format: typing.Optional[builtins.str] = None, progress: typing.Optional[typing.Any] = None) -> Discovery:
        r"""
        Find every frame on whatever is loaded
        
        `format` is one of "135", "half", "IX240", "16", "645", "66", "67",
        "68", "69", or a custom frame length in mm as a string (e.g. "56").
        Only asked for by the two of four discovery mechanisms that need a
        thumbnail pass to find frames, and even there only where the loaded
        holder does not fix or narrow it by itself, so it can usually be left
        `None`. The polarity of the film is not asked for: a frame is found by
        the bare film between two frames, which reads flat at any polarity.
        `Discovery.thumbnail`, where the mechanism took one, is what a caller
        wanting to nudge `Discovery.frames` by hand shows the operator: a
        rectangle handed to `scan_frame` needs no match in it, so a nudged one
        works the same as a detected one, just slower if the stage has to home
        first to reach it
        """
    def prime_bh(self, early: tuple[builtins.int, builtins.int, builtins.int, builtins.int]) -> None:
        r"""
        Work around the Bell&Howell first-positioning fault
        
        On BH-perforated stock (cine film), the first frame positioning after
        the framing pass can fail its verification when the target sits deeper
        than about frame 6, and the unit rewinds the film in response. Workaround is
        to rewind to a frame <=6 before transporting to a higher number.
        
        Call this once with a low frame, after discovery and before the first `scan_frame`,
        whenever the first frame you actually mean to scan is deeper than that.
        Films without BH perforations never trip the fault, so skip it there.
        """
    def scan_frame(self, frame: tuple[builtins.int, builtins.int, builtins.int, builtins.int], dpi: typing.Optional[builtins.int] = None, samples: builtins.int = 1, superfine: builtins.bool = False, infrared: builtins.bool = False, clean: builtins.bool = False, lock_white_balance: builtins.bool = True, exposures: typing.Optional[typing.Mapping[builtins.str, builtins.int]] = None, progress: typing.Optional[typing.Any] = None) -> ScanResult:
        r"""
        Focus, meter, take the pass over `frame`, and optionally clean it
        
        `frame` is `(top, left, bottom, right)`, one of `discover_frames`'s, or one
        of them moved or cropped. The pass is that rectangle at both ends. On a unit
        that positions the film by its own frame table, the rectangle is put in that
        table first, so a moved or cropped one reaches the film it asks for.
        `exposures`, keyed the way `ScanResult.exposures` is, reuses an exposure
        already decided rather than metering this frame fresh
        """
    def close(self) -> None:
        r"""
        Drop the hold on the scanner. A closed session refuses every other method
        """
    def __enter__(self) -> Session: ...
    def __exit__(self, *_args: typing.Any) -> None: ...

class TransientError(ScannerError):
    r"""
    Worth retrying
    """
    ...

class TransportError(TransientError):
    r"""
    The link to the scanner failed
    """
    ...

class UnsupportedError(ScannerError):
    r"""
    This unit or adapter cannot do that. Carries `.op` and `.reason`
    """
    ...

def init_logging(level: typing.Optional[builtins.str] = None) -> None:
    r"""
    Send the crate's `tracing` diagnostics to stderr.
    
    The extension installs no subscriber on its own, so without calling this the
    `debug!`/`trace!`/`warn!` calls throughout `session`, `scan`, `transport`, and
    `protocol` go nowhere when `nkscan` is used as a library. `level` sets the
    default (`"info"` if omitted); `RUST_LOG` always overrides it and can target
    individual modules the way it does for the CLI, e.g. `nkscan::cdb=trace`.
    Safe to call more than once. Later calls are no-ops.
    """

def list_devices() -> builtins.list[Device]:
    r"""
    Every scanner this library thinks it can drive
    """

